### ISSUE TITLE
vertical-stack-in-card shows older version

### ISSUE THREAD

**Issue by gerard33** [ludeeus/customjson#2]
**Describe the bug**
For `vertical-stack-in-card` the latest version 0.0.9 is shown, however version 0.1.0 is out (almost 2 weeks).

https://raw.githubusercontent.com/custom-cards/vertical-stack-in-card/master/VERSION

**log**
```
"vertical-stack-in-card": {
        "changelog": "https://github.com/custom-cards/vertical-stack-in-card",
        "remote_location": "https://raw.githubusercontent.com/custom-cards/vertical-stack-in-card/master/vertical-stack-in-card.js",
        "updated_at": "2019-01-10",
        "version": "v0.0.9",
        "visit_repo": "https://github.com/custom-cards/vertical-stack-in-card"
    }
```

**Comment by ludeeus** [comment]
That is correct, GitHub releases take precedence over that file.
<https://github.com/custom-cards/vertical-stack-in-card/releases>

**Comment by gerard33** [comment]
Thanks, will ask the dev to update the release.
